Makefile
Example of before/after below
```bash
[nathan@nathan-redhat dev-docs (make-help)]$ make help
Usage:
make <target>
md-lint             Lint markdown files
[nathan@nathan-redhat dev-docs (make-help)]$ make help
Usage:
make <target>
spellcheck          Spellcheck markdown files
spellcheck-sort     Sort spellcheck directory
md-lint             Lint markdown files
```
=> fix: add spellcheck and spellcheck-sort to 'make help'

docs/taxonomy-tree-organization.md
Creating a logical layout of the taxonomy tree
needs to be agreed upon. The triage team has
landed on the Wikipedia tree, and this PR
is to help justify and enforce this decision.
=> Proposed Taxonomy tree

.spellcheck-en-custom.txt, docs/github-actions-providers.md, docs/github-actions-use-policy.md
Closes https://github.com/instructlab/dev-docs/issues/12
=> Add policy document for using GitHub actions in workflows

.spellcheck-en-custom.txt, docs/sdg-repo.md
This document includes a proposal for a new repository which contains
a Python library focused on Synthetic Data Generation (SDG). This is a
discreet area of functionality that can evolve on its own with its own
group of contributors and maintainers.
Signed-off-by: Russell Bryant <rbryant@redhat.com>
=> New repository proposal: sdg

.github/mergify.yml
Automatically apply the `backend` label to any PR that touches a file
under the `docs/backend` directory.
Signed-off-by: Russell Bryant <rbryant@redhat.com>
=> mergify: automatically apply backend label

.spellcheck-en-custom.txt, docs/evaluation/eval-repo.md
=> Proposal for new Evaluation repo

.spellcheck-en-custom.txt, docs/github-actions-providers.md
Based on
https://github.com/instructlab/dev-docs/blob/main/docs/github-actions-use-policy.md#trusted-providers-of-github-actions, update the trusted providers of instructlab.
Related to https://github.com/instructlab/instructlab/issues/1218
=> Update trusted providers of github actions

docs/instructlab-app.md
This is a proposal for creating a InstructLab Application
=> InstructLab macOS App

.spellcheck-en-custom.txt, docs/cli/ilab-model-serve-backend.md
This commit introduces a new design document for the [`ilab model
serve`] command, detailing its
functionality to serve models using different backends, specifically
`llama-cpp` and `vllm`. It outlines the command structure, including
backend-specific flags and arguments, and proposes a testing strategy
for new engine integrations.
Co-authored-by: Sébastien Han <seb@redhat.com>
Signed-off-by: Ali Maredia <amaredia@redhat.com>
=> Design for serving models with different backends

.spellcheck-en-custom.txt
PR #105 needs some new words added to the spelling dictionary.
=> Update spelling per #105

docs/sdg/sdg-flow-yaml.md
Contents of file are referenced in doc; more convenient to refer to referenced file by linking to it. Using full https github link as its content in another repo.
=> Adding link to referenced file

.spellcheck-en-custom.txt, docs/sdg/sdg-api-simplification.md
See instructlab/sdg#61 for some of the discussion on this, but I've tried to summarize those discussions in the design doc.
=> Propose simplifications to the SDG API design

.spellcheck-en-custom.txt, docs/dependency-management.md
This document describes the policies for adding and updating build and runtime dependencies of all InstructLab components.
=> add requirements management policy

.spellcheck-en-custom.txt, docs/library-release-strategy.md
Resolves https://github.com/instructlab/dev-docs/issues/124
=> Add document detailing release strategy for libraries

.github/workflows/stale_bot.yml
We have lots of Dev Docs that get abandoned by their authors. This leads to confusion in the org as to what is actual policy and what is proposed. If a WIP Dev Doc is inactive, it should be closed sooner rather than later.
I have left issues alone but fixed a typo in the text.
=> stalebot: reduce amount of time for PR to turn stale

.markdownlint-cli2.yaml, .spellcheck-en-custom.txt, docs/instructlab-cli-1.0.0.md
=> Added document detailing org roadmap to Core 1.0.0

.spellcheck-en-custom.txt, docs/rag/rag-initial-code-location.md
https://github.com/instructlab/dev-docs/pull/163 failed due to some github / DCO problem, so we're trying again.
=> Second attempt to submit RAG repo location ADR because the last one failed

.spellcheck-en-custom.txt, docs/cli/ilab-processes.md
ilab should be able to run detached processes, re-attach to them, and monitor them. This document introduces a first iteration of that process management
=> Introduce dev-doc for process management

.spellcheck-en-custom.txt
In #172 , some redundant lower-case words were removed, but it turns out the spellchecker really needs them to recognize these words when they are lower case, so I am adding them back in.
=> Restore some lower-case duplicate words in spellcheck

.gitignore, .spellcheck-en-custom.txt, docs/rag/adrs/README.md, docs/rag/adrs/adr-vectordb.md, docs/rag/adrs/template.md
[#2869](https://github.com/instructlab/instructlab/issues/2869)
=> ADR: Vector store for RAG

docs/rag/adrs/granite-embeddings.md
This ADR proposes that we will use the IBM Granite Embeddings model for the vector retrieval component of our RAG solution.
=> ADR for IBM Granite Embeddings

.spellcheck-en-custom.txt, docs/sdk/instructlab-sdk.md
this document outlines the structure of the instructlab-sdk, the purpose, and the scope. The implementation specifics will be dealt with on the subsequent implementation PRs.
=> introduce document for instructlab-sdk

.spellcheck-en-custom.txt, docs/ci/dependency-constraints.md, docs/dependency-management.md
This work is being implemented in the main (instructlab/instructlab)
repository. The same approach should be applied across all the repos.
Signed-off-by: Ihar Hrachyshka <ihar.hrachyshka@gmail.com>
=> Document pip constraints CI enforcement for all dependencies

docs/ci/ec2-runners.md
Signed-off-by: Ihar Hrachyshka <ihar.hrachyshka@gmail.com>
=> Require launch-ec2-runner-with-fallback use for all ec2 runners

.github/workflows/actionlint.yml, .github/workflows/docs.yml, .github/workflows/spellcheck.yml, .github/workflows/stale_bot.yml, docs/github-actions-providers.md, docs/github-actions-use-policy.md
In all the time it was applied, no single repo cared enough to enable
`block` policy for egress network traffic. All the action did is it
produced churn where we were updating tags for the action to new
versions.
We *could* switch these actions to `block` but I'd rather remove the
requirement if in all this time we haven't seen an actual need.
Signed-off-by: Ihar Hrachyshka <ihar.hrachyshka@gmail.com>
=> Remove requirement to use harden-runner action
